### PR TITLE
Updated Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
🙂

### CODE REVIEW

**Comment by madmurphy** [comment]
Hi Heimen, thanks again for this!

Just two things.

1. In the future the emblem picker will exist only in [a separate library](https://github.com/madmurphy/libgnuisance) (Nautilus Annotations will depend on it), and when that will happen we will loose your translations concerning emblems, unless I copy your strings to **libgnuisance** as well. Is it OK for you if I do that? You could also do it yourself if you prefer.

2. The two strings “Niet-ondersteunde emblemen” and “Deze kunnen niet worden geladen. :-(” are quite long and will stretch the emblem picker. You can see it in this comparison:

english

dutch

It might not be a bad a idea to shorten them a bit if it is possible.  You can be creative. Italian had the same problem and “We coudn't render those :-(” got translated as “We are sorry :-(” (in Italian).

To make experiments, assign an unexisting emblem to a file

```
gio set -t stringv 'my_file.txt' metadata::emblems emblem-unexisting
```

and when you will open Nautilus Annotations for that file you will see that message appearing.

--madmurphy

**Comment by Vistaus** [comment]
Hi madmurphy!

1. Sure, go ahead! 🙂
2. I'm afraid that's not quite possible. I mean: I could shorten “Deze kunnen niet worden geladen. :-(”, but I can't shorten “Niet-ondersteunde emblemen” as there is no other correct or clear translation for that, even with a lot of creativity in mind.

**Comment by madmurphy** [comment]
> Sure, go ahead! slightly_smiling_face

🙂️
 
> I'm afraid that's not quite possible. I mean: I could shorten “Deze kunnen niet worden geladen. :-(”, but I can't shorten “Niet-ondersteunde emblemen” as there is no other correct translation for that.

How about “unknown” instead of “unsupported”? “Onbekend” is even shorter than the English “unsupported” (sorry, I can't speak Duch, the closest thing I know is every-day basic German).

**Comment by Vistaus** [comment]
_unknown_ is not the same as _unsupported_. But if you think that's not a problem, then I'll change it to _Onbekende emblemen_.

**Comment by madmurphy** [comment]
> But if you think that's not a problem, then I'll change it to _Onbekende emblemen_.

That is what I meant with being creative 🙂️

**Comment by Vistaus** [comment]
Alright, done! I changed that line and shortened the other one. 🙂

**Comment by madmurphy** [comment]
That's great! Thank you :)

I will make a new release with your translation in the next days.

--madmurphy

**Pull request merged**
